# Build off of Docker image made by Mohsin Shaikh 
# (mohsin.shaikh@csiro.au) 
FROM mshaikh/anaconda:latest 

# Install all dependencies for integration code 
RUN pip install rebound 
RUN pip install reboundx
RUN pip install matplotlib 

